# Generated by Django 3.1.5 on 2021-02-12 13:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('date_death', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(help_text='Выбери жанр книги', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('summary', models.TimeField(help_text='Описание книги')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogbooks.author')),
                ('genre', models.ManyToManyField(help_text='Выбери жанр книги', to='catalogbooks.Genre')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
        migrations.CreateModel(
            name='BookInstance',
            fields=[
                ('uniq_id', models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор книги', primary_key=True, serialize=False)),
                ('imprint', models.CharField(max_length=100)),
                ('date_back', models.DateField(blank=True, null=True)),
                ('book_status', models.CharField(blank=True, choices=[('О', 'Обслуживание'), ('В', 'Взаймы'), ('Н', 'Наличие'), ('Р', 'Резерв')], default='О', help_text='Наличие книги', max_length=1)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogbooks.books')),
            ],
            options={
                'ordering': ['date_back'],
            },
        ),
    ]
