# Generated by Django 3.1.5 on 2021-02-12 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['surname', 'name'], 'verbose_name': 'Автор', 'verbose_name_plural': 'Авторы'},
        ),
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['date_back'], 'verbose_name': 'Статус книги', 'verbose_name_plural': 'Статусы книг'},
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Жанр', 'verbose_name_plural': 'Жанры'},
        ),
    ]
