# Generated by Django 3.1.5 on 2021-02-13 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0002_auto_20210212_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguageBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(help_text='Выбери язык книги', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='books',
            name='language',
        ),
        migrations.AddField(
            model_name='books',
            name='language',
            field=models.ManyToManyField(help_text='Выбери язык книги', to='catalogbooks.LanguageBook'),
        ),
    ]
