# Generated by Django 3.1.5 on 2021-02-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0003_auto_20210213_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='summary',
            field=models.TextField(help_text='Описание книги'),
        ),
    ]
