# Generated by Django 3.1.5 on 2021-02-13 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0004_auto_20210213_1114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languagebook',
            options={'ordering': ['language'], 'verbose_name': 'Язык', 'verbose_name_plural': 'Языки'},
        ),
        migrations.AlterField(
            model_name='author',
            name='date_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_death',
            field=models.DateField(blank=True, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='author',
            name='surname',
            field=models.CharField(max_length=100, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogbooks.author', verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(help_text='Выбери жанр книги', to='catalogbooks.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.ManyToManyField(help_text='Выбери язык книги', to='catalogbooks.LanguageBook', verbose_name='Язык'),
        ),
        migrations.AlterField(
            model_name='books',
            name='summary',
            field=models.TextField(help_text='Описание книги', verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название книги'),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name_genre',
            field=models.CharField(help_text='Выбери жанр книги', max_length=100, verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='languagebook',
            name='language',
            field=models.CharField(help_text='Выбери язык книги', max_length=100, verbose_name='Язык'),
        ),
    ]
