# Generated by Django 3.1.5 on 2021-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0005_auto_20210213_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, help_text='<a href="https://www.isbn-international.org/content/what-isbn">ISBN номер</a>', max_length=13, null=True, unique=True, verbose_name='ISBN'),
        ),
    ]
