# Generated by Django 3.1.5 on 2021-02-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0006_books_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['date_back'], 'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книг'},
        ),
    ]
