# Generated by Django 3.1.5 on 2021-02-13 11:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0007_auto_20210213_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='catalogbooks.books', verbose_name='Книга'),
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='uniq_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Уникальный идентификатор книги', primary_key=True, serialize=False, verbose_name='Идентификатор'),
        ),
    ]
