# Generated by Django 3.1.5 on 2021-02-13 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0009_auto_20210213_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='date_back',
            field=models.DateField(blank=True, null=True, verbose_name='Текущий статус'),
        ),
    ]
