# Generated by Django 3.1.5 on 2021-02-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0011_auto_20210213_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.ManyToManyField(to='catalogbooks.Genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='books',
            name='language',
            field=models.ManyToManyField(to='catalogbooks.LanguageBook', verbose_name='Язык'),
        ),
    ]
