# Generated by Django 3.1.5 on 2021-02-17 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0013_bookinstance_debtor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['date_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),), 'verbose_name': 'Экземпляр книги', 'verbose_name_plural': 'Экземпляры книг'},
        ),
    ]
