# Generated by Django 3.1.5 on 2021-02-22 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogbooks', '0014_auto_20210217_2201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': (('create_book_bystaff', 'Create new book'),), 'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
